CREATE TABLE TB_USUARIOS (
	PK_USUARIO SERIAL PRIMARY KEY,
	NOME_USUARIO VARCHAR(30),
	ENDERECO_USUARIO VARCHAR(50),
	TELEFONE INT
);

ALTER TABLE TB_USUARIOS ADD ONLY_DROP INT;
ALTER TABLE TB_USUARIOS DROP ONLY_DROP;
ALTER TABLE TB_USUARIOS ADD IDADE_USUARIO INT;
ALTER TABLE TB_USUARIOS RENAME TELEFONE TO TELEFONE_USUARIO;
ALTER TABLE TB_USUARIOS ALTER NOME_USUARIO TYPE VARCHAR(40);

CREATE TABLE TB_CATEGORIAS(
	PK_CATEGORIA SERIAL PRIMARY KEY,
	NOME_CATEGORIA VARCHAR(30)
);

CREATE TABLE TB_AUTORES(
	PK_AUTOR SERIAL PRIMARY KEY,
	NOME_AUTOR VARCHAR(30),
	NACIONALIDADE_AUTOR VARCHAR(30)
);

CREATE TABLE TB_LIVROS(
	PK_LIVRO SERIAL PRIMARY KEY,
	TITULO_LIVRO VARCHAR(30),
	ANO_LIVRO DATE,
	GENERO_LIVRO VARCHAR(30),
	FK_AUTOR INT,
	FOREIGN KEY (FK_AUTOR) REFERENCES TB_AUTORES(PK_AUTOR)
);

ALTER TABLE tb_livros ALTER COLUMN ano_livro TYPE integer USING EXTRACT(YEAR FROM ano_livro)::integer;
ALTER TABLE tb_livros alter COLUMN titulo_livro type varchar(50);

CREATE TABLE TB_EMPRESTIMOS(
	PK_EMPRESTIMO SERIAL PRIMARY KEY,
	FK_LIVRO INT,
	FK_USUARIO INT,
	DATA_EMPRESTIMO DATE,
	DATA_DEVOLUCAO DATE,
	FOREIGN KEY (FK_LIVRO) REFERENCES TB_LIVROS(PK_LIVRO),
	FOREIGN KEY (FK_USUARIO) REFERENCES TB_USUARIOS(PK_USUARIO)
);

CREATE TABLE TB_LIVROS_CATEGORIAS (
	FK_LIVRO INT,
	FK_CATEGORIA INT,
	FOREIGN KEY (FK_LIVRO) REFERENCES TB_LIVROS(PK_LIVRO),
	FOREIGN KEY (FK_CATEGORIA) REFERENCES TB_CATEGORIAS(PK_CATEGORIA)
);

CREATE TABLE TB_ONLY_FOR_DROP(
	PK_DROP SERIAL PRIMARY KEY,
	DROP_DROP VARCHAR(30)
); 

DROP TABLE TB_ONLY_FOR_DROP;

select*from tb_autores;
select*from tb_usuarios;
select*from tb_autores;
select*from tb_emprestimos;
select*from tb_livros;
select*from tb_categorias;
SELECT*from tb_livros_categorias;
